# Generated by Django 5.2.6 on 2025-10-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo del Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
